FROM node:16-alpine3.14

WORKDIR /app
ENV NODE_ENV development

COPY package.json .
COPY package-lock.json .
RUN npm ci

COPY config ./config
COPY server.js .
COPY lib ./lib

CMD ["npm", "run", "start_docker"]
